- name: Update Wishlist Bot on VPS
  hosts: all
  remote_user: inevix
  vars:
    ansible_python_interpreter: /usr/bin/python3
    dir: "/home/{{ ansible_user }}/apps/wishlist"
    app_name: wishlist_bot
    NODE_ENV: production
  roles:
    - git_pull
    - docker_restart
