- name: Update Wishlist Bot on VPS
  hosts: all
  remote_user: inevix
  vars:
    dir: "/home/{{ ansible_user }}/apps/wishlist"
    app_name: "wishlist_bot"
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - git_pull
    - docker_restart
