version: '3.9'

services:
    db:
        image: mongo
        container_name: wishlist_db_${NODE_ENV}
        networks:
            - wishlist
        ports:
            - "27027:27017"
        volumes:
            - ../.mongo/${NODE_ENV}:/data/db
        environment:
            - MONGO_INITDB_DATABASE=wishlist_${NODE_ENV}
        command: mongod --quiet --logpath /dev/null

    app:
        image: wishlist_${NODE_ENV}
        container_name: wishlist_app_${NODE_ENV}
        depends_on:
            - db
        networks:
            - wishlist
        build:
            context: ../
            dockerfile: ./.docker/Dockerfile
            args:
                - NODE_ENV=${NODE_ENV}
        volumes:
            - ../bot:/wishlist/bot
            - ~/logs:/var/lib/docker/containers
        env_file: ../env/.env.${NODE_ENV}
        environment:
            - NODE_ENV=${NODE_ENV}
            - MONGODB_URI=mongodb://db:27017/wishlist_${NODE_ENV}
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"

networks:
    wishlist:
        name: wishlist_${NODE_ENV}
        driver: bridge
        external: false