version: '3.9'

services:
    db:
        image: mongo
        container_name: wishlist_db_${NODE_ENV}
        networks:
            - wishlist
        ports:
            - "27027:27017"
        volumes:
            - ../.mongo_${NODE_ENV}:/data/db
        environment:
            - MONGO_INITDB_DATABASE=wishlist_${NODE_ENV}
        command: mongod --quiet --logpath /dev/null

    app:
        image: wishlist_${NODE_ENV}
        container_name: wishlist_app_${NODE_ENV}
        depends_on:
            - db
        networks:
            - wishlist
        build:
            context: ../
            dockerfile: ./.docker/${NODE_ENV}.dockerfile
        volumes:
            - ../bot:/wishlist/bot
        env_file: ../env/.env
        environment:
            - NODE_ENV=${NODE_ENV}
            - MONGODB_URI=mongodb://db:27017/wishlist_${NODE_ENV}

networks:
    wishlist:
        name: wishlist_${NODE_ENV}
        driver: bridge
        external: false