- name: Build Wishlist Bot image on VPS
  docker_image:
    name: "{{ app_name }}_image"
    state: present
    force_source: true
    source: build
    build:
      path: "{{ dir }}"
      dockerfile: "./.docker/Dockerfile"
      args:
          NODE_ENV: "{{ NODE_ENV }}"

- name: Restart Wishlist Bot container on VPS
  docker_container:
    name: "{{ app_name }}"
    image: "{{ app_name }}_image"
    restart: true
    restart_policy: always
    recreate: true
    network_mode: host
    log_driver: json-file
    log_options:
      max-size: 10m
      max-file: 5
    env:
      NODE_ENV: "{{ NODE_ENV }}"
      BOT_TOKEN: "{{ BOT_TOKEN }}"
      MONGODB_URI: "{{ MONGODB_URI }}"
      ADMIN_TELEGRAM_ID: "{{ ADMIN_TELEGRAM_ID }}"
      CHANNEL: "{{ CHANNEL }}"
      GITHUB_REPO_URL: "{{ GITHUB_REPO_URL }}"
      PRINCESS_BOT_URL: "{{ PRINCESS_BOT_URL }}"
      BUYMEACOFFEE: "{{ BUYMEACOFFEE }}"
      MONOBANK: "{{ MONOBANK }}"
