name: Check and restart Docker container

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  keep_alive:
    name: Connect and Restart Container if not alive
    runs-on: ubuntu-latest
    steps:
      - name: Check and Restart Docker Container
        uses: appleboy/ssh-action@v1.0.0
        env:
          CONTAINER_NAME: wishlist_bot
        with:
          host: ${{ secrets.VPS }}
          username: inevix
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: CONTAINER_NAME
          script: |
            CONTAINER_ID=$(docker ps --filter "name=$CONTAINER_NAME" --format="{{.ID}}")
            if [ -z "$CONTAINER_ID" ]
            then
              echo "Container is not running. Restarting..."
              docker restart "$CONTAINER_NAME"
            else
              echo "Container is running."
            fi