name: Build Wishlist Bot on VPS

on:
  push:
    branches: ['main']

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run a build command
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: .ansible/main.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            ${{ secrets.VPS }} address=localhost
          options: |
            -e RELEASE=${{github.ref_name}}
            -e NODE_ENV=production
            -e VPS_APP_PATH=/home/inevix/apps/wishlist
            -e GITHUB_REPO=${{github.repository}}
            -e BOT_TOKEN=${{secrets.BOT_TOKEN}}
            -e MONGODB_URI=${{secrets.MONGODB_URI}}
            -e ADMIN_TELEGRAM_ID=${{secrets.ADMIN_TELEGRAM_ID}}
            -e GITHUB_REPO_URL=https://github.com/${{github.repository}}
            -e PRINCESS_BOT_URL=${{vars.PRINCESS_BOT_URL}}
